### ISSUE TITLE
Cannot work with ruby 1.9.2

### ISSUE THREAD

**Issue by maki-tetsu** [maki-tetsu/anodator#2]
When I use anodator on ruby-1.9.2-p290, some specs failure.

Failure/Error: @rule_set << Rule.new("1",
undefined method `to_a' for "1":String
